version: '3'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - "8000:8000"